### ISSUE TITLE
Tips on why the new boost magic wouldn't work?

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-rospack#4]
I've seen the new method of putting a static boost lib in /opt and ignoring system paths. Since this is an org with no readme... I may have missed if I have to do anything else. I removed all ros-melodic packages recently, blew away my cache and thus I *think* I rebuilt them all from scratch, however after finishing I get:
```
rospack: error while loading shared libraries: libboost_filesystem.so.1.69.0: cannot open shared object file: No such file or directory
```

I see this in build output:
```
$ aur sync --rebuild ros-melodic-rospack
...
-- Found Boost: /opt/boost1.69/include (found version "1.69.0") found components: filesystem program_options system
...
```

And:
```
$ ldd /opt/ros/melodic/bin/rospack 
	linux-vdso.so.1 (0x00007ffee6162000)
	librospack.so => /opt/ros/melodic/lib/librospack.so (0x00007fb9acf60000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fb9acd44000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb9acd2a000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fb9acb61000)
	libtinyxml2.so.7 => /usr/lib/libtinyxml2.so.7 (0x00007fb9acb49000)
	libboost_filesystem.so.1.69.0 => not found
	libboost_program_options.so.1.69.0 => not found
	libpython3.9.so.1.0 => /usr/lib/libpython3.9.so.1.0 (0x00007fb9ac784000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fb9ac63e000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fb9acfb8000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fb9ac61c000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fb9ac616000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007fb9ac611000)
```

```
$ ls /opt/boost1.69/lib/libboost_filesystem.so.1.69.0 
/opt/boost1.69/lib/libboost_filesystem.so.1.69.0
```

Any insights into what could be going wrong here?

**Comment by jwhendy** [comment]
Has someone tested this method? Unless this is just me, this is more widespread.

```
$ roscore
/opt/ros/melodic/lib/rosout/rosout: error while loading shared libraries: libboost_thread.so.1.69.0: cannot open shared object file: No such file or directory

$ rviz
rviz: error while loading shared libraries: libboost_filesystem.so.1.69.0: cannot open shared object file: No such file or directory
```
There are a bunch of threads on how to make this magic work. I wondered if `BOOST_INCLUDEDIR` and/or `BOOST_LIBRARYDIR` are also needed, but so far nothing has worked. Upon each change, I'm `rm -rf ./src ./pkg` and remaking with `makepkg`, then doing this and get the same results:

```
$ ldd pkg/ros-melodic-rospack/opt/ros/melodic/bin/rospack 
	linux-vdso.so.1 (0x00007ffc87aaa000)
	librospack.so => /opt/ros/melodic/lib/librospack.so (0x00007f62cf36e000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f62cf152000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f62cf138000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f62cef6f000)
	libtinyxml2.so.7 => /usr/lib/libtinyxml2.so.7 (0x00007f62cef57000)
	libboost_filesystem.so.1.69.0 => not found
	libboost_program_options.so.1.69.0 => not found
	libpython3.9.so.1.0 => /usr/lib/libpython3.9.so.1.0 (0x00007f62ceb92000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f62cea4c000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f62cf3c6000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f62cea2a000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f62cea24000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f62cea1f000)
```

[This article](https://scaron.info/blog/cmake-can-use-a-local-boost.html) seems relevant, but I think all of the settings from the article were already in `src/build/CMakeCache.txt` except for `CMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON` which didn't affect my results. I'm confused!

**Comment by fmauch** [comment]
Did you set the `LD_LIBRARY_PATH` variable? Obviously, ldd doesn't find them, if the custom folder isn't inside the `LD_LIBRARY_PATH`.

```
$ echo $LD_LIBRARY_PATH
/opt/boost1.69/lib:/opt/boost1.69/lib:
```

It's true, that this isn't mentioned anywhere, I'm not sure whether anybody except from @bionade24 and me are actually using those...

**Comment by jwhendy** [comment]
@fmauch Thanks for the help. I'm unfamiliar with that and thought the point of setting these flags was to sort of "bake" this in to the ROS binaries that get built in order to maintain a separation of system stuff (looking for current boost) vs. ROS (looking for 1.69). Is that not the aim/the mechanism going on here? Any downsides to having this set system wide?

From a practical standpoint, would I do this via ~/.bashrc? My current is, this, though I admit I'm not sure where it's being set from.
```
$ echo $LD_LIBRARY_PATH
/home/jwhendy/catkin_ws/devel/lib:/opt/ros/melodic/lib
```

> I'm not sure whether anybody except from @bionade24 and me are actually using those...

Can you let me know what you mean by "those"?

**Comment by jwhendy** [comment]
Again, consider me an ldd/library complete noob... but [the article](https://scaron.info/blog/cmake-can-use-a-local-boost.html) I linked above refers to this approach (**edit:** "this approach" = brute forcing with `LD_LIBRARY_PATH`), which jives with my intuition it would be superior to let ROS use this custom boost sandbox vs. pushing this system wide? Dunno, but could this be relevant to a more comprehensive/future proof approach?

>RPATH is a list of directories that is directly written into your executable or shared object and tells the linker where to look for libraries. It has precedence over the LD_LIBRARY_PATH system-wide variable, as explained in this page on CMake RPATH handling.

>A dirty solution to the "not found" problem would be to add the local Boost 1.64 libraries to LD_LIBRARY_PATH. But then, they would also be visible in other projects trying to link to Boost, which can be problematic. We will rather set RPATH to avoid this and keep things local.

Then the proposed approach is:
```
// Use same RPATH at install and build
CMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON
```

**Comment by bionade24** [comment]
@jwhendy Nice to hear from you again!

> I've seen the new method of putting a static boost lib in /opt and ignoring system paths. 

boost1.69 isn't static, it's just the old version, melodic officially complies with.
> Since this is an org with no readme... I may have missed if I have to do anything else. I removed all ros-melodic packages recently, blew away my cache and thus I _think_ I rebuilt them all from scratch, however after finishing I get:

We have now README, because adding it to any PKGBUILD would need to add it as source or AURWeb complains. I updated the Arch Wiki ros entry, though. But as you'll see in this thread, those issue does have nothing to do with the new flags for catkin I added to the wiki page.

> -- Found Boost: /opt/boost1.69/include (found version "1.69.0") found components: filesystem program_options system

So you have to be installed this, that's were I really wondering. I'm not really using ROS anymore, so I only tested the boost1.69 switch immedeately afterwards.
> Any insights into what could be going wrong here?

I messed up the entry in `ld.so.cond.d` after "cleaning up" the PKGBUILD. https://aur.archlinux.org/cgit/aur.git/commit/?h=boost1.69&id=11e666fac82e95e3fe39613aa4c33f12d9e4add1 
Edit: If you look at the diff of the commit in the URL, only the last 2 removed lines are relevant.

I fixed it, it's already in the AUR, as boost1.69 is not part of the GH orga. CD still runs, binary package available soon. Sorry, my bad fault.

**Comment by fmauch** [comment]
> @fmauch Thanks for the help. I'm unfamiliar with that and thought the point of setting these flags was to sort of "bake" this in to the ROS binaries that get built in order to maintain a separation of system stuff (looking for current boost) vs. ROS (looking for 1.69). Is that not the aim/the mechanism going on here? Any downsides to having this set system wide?

Linking and library lookup are two separate mechanisms which basically make using shared libraries possible, after all. The modifications to the PKGBUILDS tell the **linker** where to lookup the libraries, while the `LD_LIBRARY_PATH` tell the **runtime environment** where to lookup those libraries.

It would be possible to patch the package that provides `/opt/ros/melodic/setup.sh` (**Edit**: Which would be ros-melodic-catkin) as this is setting ROS specific variables (see below).

> 
> From a practical standpoint, would I do this via ~/.bashrc? My current is, this, though I admit I'm not sure where it's being set from.

It can be anywhere in your environment setup. Yes, the `~/.bashrc` file is a suitable place, just make sure to set it before sourcing ROS (see further below).

> 
> ```
> $ echo $LD_LIBRARY_PATH
> /home/jwhendy/catkin_ws/devel/lib:/opt/ros/melodic/lib
> ```
> 

ROS source scripts modify this variables for the same reasons as mentioned above. You have libraries inside your local workspace and in `/opt/ros/melodic/lib` that your runtime environment should be able to find. ROS will append your local workspace and the global ROS library location to your `LD_LIBRARY_PATH` when building your workspace for the first time and replace it with this value on future source commands of your workspace's `devel/setup.[bash|zsh]`.

> Can you let me know what you mean by "those"?

Those "ROS melodic" packages :-)

**Comment by bionade24** [comment]
> > @fmauch Thanks for the help. I'm unfamiliar with that and thought the point of setting these flags was to sort of "bake" this in to the ROS binaries that get built in order to maintain a separation of system stuff (looking for current boost) vs. ROS (looking for 1.69). Is that not the aim/the mechanism going on here? Any downsides to having this set system wide?
> 
> Linking and library lookup are two separate mechanisms which basically make using shared libraries possible, after all. The modifications to the PKGBUILDS tell the **linker** where to lookup the libraries, while the `LD_LIBRARY_PATH` tell the **runtime environment** where to lookup those libraries.

"The good way" is to add a file with the path under `ld.so.conf.d` and not manipulating `LD_LIBRARY_PATH` all the time. I accidentally deleted `/etc/ld.so.conf.d/boost1.69.conf` in one commit, see my first reply.

**Comment by bionade24** [comment]
@fmauch If you run into tsuch an issue next time, please just not fix it for now but at least open a bug. When I'm not constantly using ROS, I can't find all bugs anymore.

**Comment by fmauch** [comment]
I didn't consider this a bug, as this would be my normal way of handling libraries in non-standard installation paths. I wasn't familiar with `/etc/ld.so.conf.d`.

So, modifying my local `LD_LIBRARY_PATH` seemed like the obvious necessary step for me :-)

**Comment by bionade24** [comment]
> I didn't consider this a bug, as this would be my normal way of handling libraries in non-standard installation paths. I wasn't familiar with `/etc/ld.so.conf.d`.
> 
> So, modifying my local `LD_LIBRARY_PATH` seemed like the obvious necessary step for me :-)

Now you know it, of course there should be no need for manual invervention when you install something ;)  (Looking at ROS which still is unable to add their stuff under /etc because they think manipulating user shell rc files is the best solution to serve multiple installations on one root)

**Comment by bionade24** [comment]
I can confirm now that with the updated boost package out of my repo, roscore and rqt work.

**Comment by jwhendy** [comment]
@bionade24 good to be "back," even if I'm always here when challenges show up :) I appreciate the quick help.

> boost1.69 isn't static

My terminology probably wasn't correct. What I meant is that I viewed "static" being the opposite of "dynamic" and though perhaps our compiling against boost1.69 wasn't working when going to run, and that this flag could be relevant to force it to be static. Static only in the sense of "look where I told you when building," (static) not "check paths on the fly" (dynamic). Again, this was totally concocted in my head and I was just guessing.

> So you have to be installed this

Definitely installed!
```
$ pacman -Q |grep boost
boost 1.75.0-2
boost-libs 1.75.0-2
boost1.69 1.69.0-8
boost1.69-libs 1.69.0-8
```

Thanks for the quick fix. The individual calls at least look up their libraries, but I have errors when trying to run one of my launch files. Think this [might be python3.9 related](https://github.com/Azure/azure-cli/issues/15441#issuecomment-705400107). I'll dig around and can start a new issue. I tried turtle_tf2 as a backup and encounter it as well.
```
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python3.9/site-packages/rospy/impl/tcpros_service.py", line 522, in call
    responses = transport.receive_once()
  File "/opt/ros/melodic/lib/python3.9/site-packages/rospy/impl/tcpros_base.py", line 737, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/melodic/lib/python3.9/site-packages/rospy/impl/tcpros_base.py", line 109, in recv_buff
    raise TransportTerminated("unable to receive data from sender, check sender's logs for details")
rospy.exceptions.TransportTerminated: unable to receive data from sender, check sender's logs for details

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/melodic/lib/turtle_tf2/turtle_tf2_listener.py", line 50, in <module>
    spawner(4, 2, 0, turtle_name)
  File "/opt/ros/melodic/lib/python3.9/site-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/melodic/lib/python3.9/site-packages/rospy/impl/tcpros_service.py", line 532, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python3.9/site-packages/rospy/core.py", line 615, in _ros_atexit
    signal_shutdown('atexit')
  File "/opt/ros/melodic/lib/python3.9/site-packages/rospy/core.py", line 598, in signal_shutdown
    if t.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
```

**Comment by jwhendy** [comment]
Thanks for helping explain @fmauch ! Indeed, you are not the only ones using these. I was using Ubuntu, but love arch and got tired of always rebooting to do ROS stuff. I've actually run into your stuff before as I'm using Universal_Robots_ROS_Driver at work to run a UR10 :)

**Comment by jwhendy** [comment]
Just piling on here, but my setup after a complete rebuild (was functioning before holidays in late Nov) is definitely not happy. The `isAlive` thing seems real and is fixed [upstream](https://github.com/ros/ros_comm/pull/2092). I still can't run `turtle_tf2` or rviz (seg fault) (edit: after building from upstream git and those isAlive errors went away).

Would having fixed just boost itself require rebuilding against it? I must have gone awry somewhere, but am not sure. Typically I just build ros-melodic-ros-base, ros-melodic-desktop, ros-melodic-desktop-full, ros-melodic-moveit in order, and then fill in any gaps when I try to build catkin_ws. Wondering if anyone else who's been running ROS this whole time has had issues post boost, python3.9 and/or anything else?

**Comment by bionade24** [comment]
> Just piling on here, but my setup after a complete rebuild (was functioning before holidays in late Nov) is definitely not happy. The `isAlive` thing seems real and is fixed [upstream](https://github.com/ros/ros_comm/pull/2092). I still can't run `turtle_tf2` or rviz (seg fault) (edit: after building from upstream git and those isAlive errors went away).

Seems like we have to patch it, too as the fix is for noetic. Needing to patch everything was the reason I wanted to go back to boost1.69 forever, which is the official boost version.

> Would having fixed just boost itself require rebuilding against it? I must have gone awry somewhere, but am not sure. Typically I just build ros-melodic-ros-base, ros-melodic-desktop, ros-melodic-desktop-full, ros-melodic-moveit in order, and then fill in any gaps when I try to build catkin_ws. Wondering if anyone else who's been running ROS this whole time has had issues post boost, python3.9 and/or anything else?

No, because boost1.69 is linked dynamically and its ABI will never change again, there never will be a need to rebuild for boost after you have rebuilt your catkin_workspace once. Someone had problems rebuilding his catkin workspace, but I can't remember aynone else complaining. We definately have more users when I count the accesses to my repo. https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aros-melodic-arch+ Guess they're all geniusses fixing everything locally ;) But the most people moved on to noetic and only a few people still use melodic. So one good source for testing for is the CI, which looks fine except some packages, some not even in this org, where I was too lazy to fix until now. 
https://abs-cd.oscloud.info/cd_manager/overview/?sort=build_status

**Comment by fmauch** [comment]
I haven't been actively using my ROS system since late November, as well. I noticed some glitches, such as I have a segfault in one node, but I haven't found the time to look into it, yet. I can confirm that rviz also crashes for me :-(
